PermitRootLogin no
# PasswordAuthentication is set to no because if you dont have a key setup you will be locked out of the system
PasswordAuthentication no
PubkeyAuthentication yes
ClientAliveInterval 300
ClientAliveCountMax 2
